function designkit = cirDesignkitInit(designkitName, simulator)
% The field printParamTuple is a cell array that is constructed
% as follows. It consists of groups of three elements. The first element of
% each group is a string that corresponds to a circuit element type. The second
% element contains a list of strings that correspond to the parameters that
% can be printed to or modified in a circuit simulation file. The third
% element is a list of the same length as the second element. Every element
% in this list is a string that is used in the simulation file for the value
% of the corresponding parameter of the first element. For example, for a
% resistor, the first element is 'res'. If now the second element is {'val'}
% and  the third element is {'r'}, then the field "val" of
% a resistor is represented by "r" (this corresponds to the Spectre syntax).
% The possible strings in the second elements of each trio of this list should
% belong to the fields circuit.allowedPrintFields.res,
% circuit.allowedPrintFields.cap, ... 
%
%  (c) IMEC, 2004
%  IMEC confidential 
%


designkit.name = designkitName;

switch simulator
  case {'spice', 'hspice', 'smartspice'}
    designkit.printParamTuple = {'res', {'val'}, {'val'}, 'cap', {'val'}, {'val'}, 'ind', ...
	{'val'}, {'val'}, 'v', {'val'}, {'val'}, 'i', {'val'}, {'val'}, 'nmos', ...
	{'w', 'lg', 'as', 'ad', 'ps', 'pd', ... 
	'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'}, 'pmos', {'w', 'lg', ...
	'as', 'ad', 'ps', 'pd', 'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'} ...
	};
  case 'spectre'
    % now we install the default design kit for spectre. This can be overridden
    % below.
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult'}, {'w', 'l', 'as', ...
	'ad', 'ps', 'pd', 'm'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
	'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'}};
  otherwise
    warning('simulator unknown or not specified');
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult'}, {'w', 'l', 'as', ...
	'ad', 'ps', 'pd', 'm'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
	'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'}};
end

designkit.simulator = simulator;


switch designkitName
  case 'nanoRFfin'
    designkit.tech.node = 45e-9;
    designkit.tech.source = 'MM11 ARF';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'lg', 'nFingers', 'nFins'}, {'L', 'Nfinger', 'Nfin'}, 'pmos', ...
	{'lg', 'nFingers', 'nFins'},  {'L', 'Nfinger', 'Nfin'}};
    designkit.psf.DcExtraString.nmos = '.nFINintr';
    designkit.psf.DcExtraString.pmos = '.nFINintr';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'ft', '', '', '', '', '', '', ''};
    designkit.spectre.paramsOfInterestNames.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmb', ...
	'gds', 'vth', 'vdss', 'fug', 'cgs', 'cgsol', 'cgd', 'cgdol', 'csb', ...
	'cdb', 'fknee'};
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;

    
  case 'nanoRF'
    designkit.tech.node = 45e-9;
    designkit.tech.source = 'MM11 ARF';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'nFingers'}, {'w', 'l', 'FOLD'}, 'pmos', ...
	{'w', 'lg', 'nFingers'},  {'w', 'l', 'FOLD'}};
    designkit.psf.DcExtraString.nmos = '.dMOSintr';
    designkit.psf.DcExtraString.pmos = '.dMOSintr';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'ft', '', '', '', '', '', '', ''};
    designkit.spectre.paramsOfInterestNames.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmb', ...
	'gds', 'vth', 'vdss', 'fug', 'cgs', 'cgsol', 'cgd', 'cgdol', 'csb', ...
	'cdb', 'fknee'};
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
 
  case 'impact2'
    designkit.tech.node = 90e-9;
    designkit.tech.source = 'MM11 IMPACT';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'nFingers'}, {'Wnom', 'Lnom', 'FOLD'}, 'pmos', ...
	{'w', 'lg', 'nFingers'},  {'Wnom', 'Lnom', 'FOLD'}};
    designkit.psf.DcExtraString.nmos = '.minicall_2.minicall_1.mne_1';
    designkit.psf.DcExtraString.pmos = '.minicall_2.minicall_1.mpe_1';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'ft', '', '', '', '', '', '', ''};
    designkit.spectre.paramsOfInterestNames.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmb', ...
	'gds', 'vth', 'vdss', 'fug', 'cgs', 'cgsol', 'cgd', 'cgdol', 'csb', ...
	'cdb', 'fknee'};
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
  case 'st'
    designkit.tech.node = 350e-9;
    designkit.tech.source = 'ST';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'nFingers'}, {'w', 'l', 'nFingers'}, 'pmos', {'w', ...
	'lg', 'nFingers'}, {'w', 'l', 'nFingers'} };
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
    %    designkit.spectreFieldNames = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
    %	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb', ...
    %	'vth'};  

  case 'umc18'
    designkit.tech.node = 180e-9;
    designkit.tech.source = 'UMC';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult'}, {'w', 'l', 'as', ...
	'ad', 'ps', 'pd', 'm'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
	'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'}};
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;

 case 'umc13'
    designkit.tech.node = 130e-9;
    designkit.tech.source = 'UMC';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult'}, {'w', 'l', 'as', ...
	'ad', 'ps', 'pd', 'm'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
	'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'}};
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;

 case 'umc90'
    designkit.tech.node = 90e-9;
    designkit.tech.source = 'UMC';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult','nFingers'}, {'w', 'l', 'as', ...
	'ad', 'ps', 'pd', 'm','nf'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
	'mult','nFingers'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm', 'nf'}};
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;    
    
case 'umc65'
    designkit.tech.node = 65e-9;
    designkit.tech.source = 'UMC';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult','nFingers'}, {'w', 'l', 'as', ...
	'ad', 'ps', 'pd', 'm','nf'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
	'mult','nFingers'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm', 'nf'}};
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
    
case 'tsmc28'
    designkit.tech.node = 28e-9;
    designkit.tech.source = 'TSMC';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'nFingers'}, {'w', 'l', 'nFingers'}, 'pmos', {'w', ...
	'lg', 'nFingers'}, {'w', 'l', 'nFingers'} };
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
    
  case 'sc45'
    designkit.tech.node = 45e-9;
    designkit.tech.source = 'SPDT';
    designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
	'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
	'nmos', {'w', 'lg', 'nFingers'}, {'w', 'l', 'nFingers'}, 'pmos', {'w', ...
	'lg', 'nFingers'}, {'w', 'l', 'nFingers'} };
    designkit.psf.DcExtraString.nmos = '';
    designkit.psf.DcExtraString.pmos = '';
    designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
    designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
    designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
    %    designkit.spectreFieldNames = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
    %	'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb', ...
    %	'vth'};  
    
  otherwise
  designkit.printParamTuple = {'res', {'val'}, {'r'}, 'cap', {'val'}, {'c'}, ...
      'ind', {'val'}, {'l'}, 'v', {'val'}, {'dc'}, 'i', {'val'}, {'dc'}, ...
      'nmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', 'mult'}, {'w', 'l', 'as', ...
      'ad', 'ps', 'pd', 'm'}, 'pmos', {'w', 'lg', 'as', 'ad', 'ps', 'pd', ...
      'mult'}, {'w', 'l', 'as', 'ad', 'ps', 'pd', 'm'}};
  designkit.psf.DcExtraString.nmos = '';
  designkit.psf.DcExtraString.pmos = '';
  designkit.spectre.paramsOfInterest.nmos = {'ids', 'vgs', 'vds', 'vsb', 'gm', 'gmbs', ...
      'gds', 'vth', 'vdsat', 'cgs', 'cgd', 'cgg', 'csb', 'cdb'};
  designkit.spectre.paramsOfInterestNames.nmos = designkit.spectre.paramsOfInterest.nmos;
  designkit.spectre.paramsOfInterest.pmos = designkit.spectre.paramsOfInterest.nmos;
  designkit.spectre.paramsOfInterestNames.pmos = designkit.spectre.paramsOfInterestNames.nmos;
end

if strcmp(simulator, 'spectre')
  if (length(designkit.spectre.paramsOfInterestNames.nmos) ~= ...
	length(designkit.spectre.paramsOfInterest.nmos)) | ...
	(length(designkit.spectre.paramsOfInterestNames.pmos) ~= ... 
	length(designkit.spectre.paramsOfInterest.pmos))
    error(strcat('length of cell arrays in the fields ', ...
	'.spectre.paramsOfInterest and .spectre.paramsOfInterestNames', ...
	' not equal')); 
  end
end

